### ISSUE TITLE
Console Spam on player join

### ISSUE THREAD

**Issue by CyreX12** [montlikadani/TabList#145] opened 2020-05-08 21:30 UTC
.... [23:09:13 WARN]: java.io.FileNotFoundException: https://raw.githubusercontent.com/montlikadani/TabList/master/plugin.yml
>.... [23:09:13 WARN]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1896)
>.... [23:09:13 WARN]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
>.... [23:09:13 WARN]: at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
>.... [23:09:13 WARN]: at java.net.URL.openStream(URL.java:1068)
>.... [23:09:13 WARN]: at hu.montlikadani.tablist.bukkit.utils.UpdateDownloader$1.run(UpdateDownloader.java:38)
>.... [23:09:13 WARN]: at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
>.... [23:09:13 WARN]: at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
>.... [23:09:13 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
>.... [23:09:13 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>.... [23:09:13 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>.... [23:09:13 WARN]: at java.lang.Thread.run(Thread.java:748)

Server: 1.14.4 Paper (4core, 4gb ram)
Plugin: v5.4.0

**Comment by CreepyCre** [comment] 2020-05-08 22:22
The issue is related to a restructuring of the project files. It will be fixed in the next update.

**Closed** 2020-05-09 06:04 UTC
