### ISSUE TITLE
Spectator mode warn spam

### ISSUE THREAD

**Issue by 69b69t** [montlikadani/TabList#374] opened 2022-12-29 04:03 UTC
### Type of bug

Error in console

### TabList version

[19:51:29 INFO]: TabList version 5.6.6 [19:51:29 INFO]: An ultimate animated tablist [19:51:29 INFO]: Author: montlikadani

### Software version

[19:51:45 INFO]: Checking version, please wait... [19:51:46 INFO]: Current: git-Purpur-1879 (MC: 1.19.3)* * You are running the latest version

### Relevant plugins

TabList  and ProtocolLib

### Console error (if applicable)

https://paste.gg/p/anonymous/b482270a97544a6486ea3ef84982da02

### TabList configuration files

https://paste.gg/p/anonymous/57eae00aa43444789f1779a478b643f5

### Bug description

How to reproduce:

1. Use default config
2. change remove-gray-color-from-tab-in-spectator from "false" to "true"
3. enjoy the free errors

**Comment by montlikadani** [comment] 2022-12-29 07:27
This has already been fixed in our [newest build](https://github.com/montlikadani/TabList/actions/workflows/gradle.yml), and duplicate of https://github.com/montlikadani/TabList/issues/373

**Closed by montlikadani** 2022-12-29 07:27 UTC
Labels: Type: Unconfirmed
