### ISSUE TITLE
Sorting not working

### ISSUE THREAD

**Issue by TyskiRycerz** [montlikadani/TabList#339] opened 2022-04-04 14:43 UTC
### Type of bug

Other

### TabList version

[16:38:48 INFO]: TabList version 5.6.2 [16:38:48 INFO]: An ultimate animated tablist [16:38:48 INFO]: Author: montlikadani

### Software version

 [16:39:07 INFO]: This server is running Paper version git-Paper-267 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e7d928a) You are 10 version(s) behind Download the new version at: https://papermc.io/downloads

### Relevant plugins

[16:39:33 INFO]: Plugins (74): AAC5, AdvancedBan, AdvancedNMotd, ajParkour, AngelChest, AnnouncerPlus, ArmoredElytra, AuthMe, BanItem, BeastTokens, BeastWithdraw, BetterTeams, BotSentry, BountyHunters, Brewery, ChatInjector, ChestShop, ChestSort, Chunky, CMILib, ColoredSigns, CombatLogX, CommandPanels, CoreProtect, CrazyEnchantments, DailyRewardsPlus, EasyClearChat*, eGlow, Essentials, EssentialsChat, EssentialsSpawn, eZProtector, GSit, HolographicDisplays, InfoBoardReborn*, InteractiveBooks, InventoryRollbackPlus, Jobs, LuckPerms, MarriageMaster, mcMMO, Multiverse-Core, MVdWPlaceholderAPI*, PartyAndFriends, PlaceholderAPI, PlayerWarps, PlayTime*, ProtectionStones, ProtocolLib, Quests, RandomTeleport, ServerMarket, ShopGUIPlus, SimpleRename, SirBlobmanCore (SirBlobmanAPI, XSeries), SkinsRestorer, SklepMC*, Skript, spark, StaffChat, SuperVanish, TabList, TimeVote, TradeMe, UltimateTimber, Vault, ViaBackwards, ViaVersion, VoidGen, VoxelSniper, WeatherVote, WordGamesPlus*, WorldEdit, WorldGuard

### Console error (if applicable)

No errors

### TabList configuration files

config.yml:
https://paste.gg/p/anonymous/1afc1ed9271647ed81ed8135fd296e26

groups.yml:
https://paste.gg/p/anonymous/06cd8fd406604420bc5b67f98b28652b

### Bug description

Well, tablist sorting is not working correctly for me and I don't know if I have made something wrong in configurations or what. Effect can be seen on the image below
![Przechwytywanie](https://user-images.githubusercontent.com/89855119/161568970-cfcf4d8a-ea39-4bf9-9189-f23a11550997.PNG)

**Comment by purpleskier1** [comment] 2022-04-05 21:07
I am having the exact same issue and have my sort-priorities set correctly as well.

**Comment by Durgesh196999** [comment] 2022-04-08 13:57
Bro the tablist supports luckperm

**Comment by TyskiRycerz** [comment] 2022-04-10 09:48
What I noticed now is that when I created some new ranks they didn't automatically appear in groups.yml. As far as I remember (and I could be wrong) new ranks should appear inside that file. Was there any change made with that group.yml file that could make it not work correctly?

**Comment by montlikadani** [comment] 2022-04-10 11:33
If the option `sync-plugins-groups-with-tablist` in config is enabled, it will synchronize the created groups in luckperms through Vault. If one of the plugin like a permission plugin or Vault is missing, it will not sync with it. Also it needs a reload for the TL plugin to apply.

**Comment by montlikadani** [comment] 2022-04-10 11:34
Also for this issue you created, try to remove some plugins like InfoBoardReborn, it may be conflicts with TL as tablist uses the same scoreboard mechanics for appending groups prefixes for players.

**Comment by TyskiRycerz** [comment] 2022-04-10 15:39
I removed IBR and nothing changed, any idea on different plugin? Or should I partially remove all of them?

**Comment by purpleskier1** [comment] 2022-04-16 23:45
Yeah the sorting still isn't working for me but I noticed that it is now sorting the Tab in reverse alphabetical order by player name.

**Comment by TyskiRycerz** [comment] 2022-04-18 19:37
> Yeah the sorting still isn't working for me but I noticed that it is now sorting the Tab in reverse alphabetical order by player name.

Not in my case hahah
Now some players don't even have prefixes on tablist :v

**Comment by purpleskier1** [comment] 2022-04-25 03:11
Tyski were you using this plugin and the sorting was working and then just randomly a month ago without changing anything it stopped working? Because that is what happened for me. I have been waiting for this to get resolved but it is still an unconfirmed bug 3 weeks later.

**Comment by montlikadani** [comment] 2022-04-25 06:15
Literally I don't know how to fix this. I tested with 2 players and the sorting was worked properly.

**Comment by PaBox** [comment] 2022-05-02 23:59
Well, at least for me I have found, that enabling afk players to drop to the end of the list - they will. But they will not come up to their old position. 
Join with an admin first, then with the normal player. Go afk with the admin and the non-afk - you will still be at the end of the list.
Also my sorting has not been working correctly when using the Group-Names, I am rather using the permissions so their could be an error-source at that point as well. Just suggesting more here to find the issue as this is quite annoying...but I just turned off the afk-ordering and now everything is fine....so its just the 2 things I think ^^

**Comment by purpleskier1** [comment] 2022-07-01 02:04
So when I updated Purpur to 1.19 version #1669 from 1.18.2 on June 22nd the sorting started working correctly. Randomly broke again yesterday June 29th.

**Comment by Loubafritz** [comment] 2022-07-17 14:13
I have the same issue...

**Comment by montlikadani** [comment] 2022-07-22 11:36
Can someone test the new build if the sorting works? See [Actions](https://github.com/montlikadani/TabList/actions/workflows/gradle.yml) page, select first one and find Artifacts.

**Comment by Loubafritz** [comment] 2022-07-29 11:39
I have test and it's not working

**Comment by PandaUwUxd** [comment] 2022-07-31 06:13
I have the same issue...

Version: 5.6.3
Server jar: purpur-1.19-1734

https://media.discordapp.net/attachments/996959824917037126/1003182812372942929/Captura_de_pantalla_2022-07-31_010949.png

**Comment by TheNety** [comment] 2022-07-31 08:00
Could you guys also share your config and groups file + your plugins list? We're not able to reproduce this issue

**Comment by PandaUwUxd** [comment] 2022-07-31 17:50
PLugins:
https://cdn.discordapp.com/attachments/996959824917037126/1003358028743065710/Captura_de_pantalla_2022-07-31_124542.png


Groups:
https://paste.ofcode.org/BEXLYv7dvX6ge85dHFb3Br

Config: (maybe is not all ok, im tryed some things abouts sort)
https://paste.ofcode.org/aY9x8qQnydC6BDJ9maKzB5

**Comment by purpleskier1** [comment] 2022-08-18 01:24
[Groups.txt](https://github.com/montlikadani/TabList/files/9366914/Groups.txt)
[Config.txt](https://github.com/montlikadani/TabList/files/9366916/Config.txt)
Plugins (90): ActionHealth, AltDetector, ArmorStandTools, AuctionHouse, BetterRTP, BlockLocker, Bounties, Brewery, ChestShop, Chunky, ClearFog, CMILib, CommandPanels, CoreProtect, CraftBook, CraftingStore, DecentHolograms, DiscordSRV, DoorsReloaded, Duels, DyedBackpacks, dynmap, Dynmap-Essentials*, Dynmap-Towny, Dynmap-WorldGuard*, EconomyShopGUI, EcoPower, eGlow, EliteMobs, EntityDetection, EpicRename, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, ExcellentCrates, ExoticGarden, ExtraGear, ExtraTools, floodgate, Geyser-Spigot, HeadDatabase, InfinityExpansion, InventoryRollbackPlus, ItemRename*, Jobs, JoinEventsPro, LiteBans, LuckPerms, Magic, mcMMO, Movecraft, Movecraft-Repair, Multiverse-Core, MyPet, Networks, NewGods, NexEngine, NoPlugins, OpenInv, Pain, PlaceholderAPI, Plan, PlayerStatueBuilderX, PlayerWarps, PlugManX (PlugMan), ProtocolLib, Replenish, SFCalc, Slimefun, SlimefunLuckyBlocks, SlimyTreeTaps, spark, TabList, TimeVote, Towny, TownyChat, TownyFlight, UltimateTimber, VanishNoPacket, Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, WeatherVote, WorldEdit, WorldGuard, WorldGuard-Towny

**Comment by montlikadani** [comment] 2022-08-18 09:38
This is not related to this issue at all.

**Comment by TastaMax** [comment] 2022-12-27 15:31
I have the same problem. Sometimes the sorting works sometimes not. A tablist reload fixes the sorting, but after some time the problem occurs again. Latest Paper Version 1.19.3 #362

The sort-priority does not work reliably.

**Comment by montlikadani** [comment] 2023-02-02 19:01
@TyskiRycerz created a ticket on discord that describes it was caused by eGlow plugin. After removing this resource, the sorting worked. I don't know if this works for anyone else?

**Comment by GGVGG** [comment] 2023-06-17 17:47
For me sorting is still broken. eGlow is not installed.

**Comment by TastaMax** [comment] 2023-06-18 09:24
I think that not only eGlow makes a problem. 
I did not have eGlow and it did not work properly. 
Maybe it is basically an error in the sorting... Unfortunately there is also no debugging... 

Well now I have my own Tablist plugin which works better. :)

**Comment by montlikadani** [comment] 2023-10-31 17:02
https://github.com/montlikadani/TabList/commit/e3d8ee0a244cd9a654523f12a1f64138647b1596

Hopefully this fixes the sorting issue. I am reopening this issue if someone interested in testing this. The build is available on [Actions](https://github.com/montlikadani/TabList/actions/workflows/gradle.yml) page, select the first one and find Artifacts.

**Comment by montlikadani** [comment] 2023-11-01 17:09
Looks like the above commit actually fixes this issue. Closing as resolved

**Closed by montlikadani** 2023-11-01 17:09 UTC
Labels: Platform: Bukkit
