### ISSUE TITLE
Bug with geysermc

### ISSUE THREAD

**Issue by cicatrice74** [montlikadani/TabList#375] opened 2023-01-01 09:42 UTC
### Type of bug

Error in console

### TabList version

[10:42:21 INFO]: TabList version 5.6.6 [10:42:21 INFO]: An ultimate animated tablist [10:42:21 INFO]: Author: montlikadani

### Software version

[10:42:36 INFO]: Checking version, please wait... [10:42:36 INFO]: This server is running Paper version git-Paper-366 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 8d7d927) You are running the latest version Previous version: git-Paper-307 (MC: 1.19.2)

### Relevant plugins

antiRedstoneClock, ArmorStand-Limiter, ArtMap, BattlePass, BlocksHub, BuycraftX, ChatManager, Chunky, Citizens, ClearLag, CoreProtect, CraftBook, CrazyAuctions, CrazyCrates, CreativeItemControl, DeluxeMenus, EpicGuard, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, eZProtector, FarmControl, FastAsyncWorldEdit (WorldEdit), FeatherBoard, FireworkCommand*, floodgate, Geyser-Spigot, GriefPrevention, HolographicDisplays, JW_Piano, LibsDisguises, LiteBans, LuckPerms, Matrix, MinecraftITALIA-Votifier*, Multiverse-Core, Multiverse-Inventories, NametagEdit, PlaceholderAPI, PlayerParticles, PlotSquared, ProtocolLib, RealEstate, ServerListPlus, SkinsRestorer, Skulls, TabList, TCPShield, TradeSystem, Vault, Votifier, VotingPlugin, Wild, WorldGuard, WorldGuardExtraFlags

### Console error (if applicable)

[10:39:40 WARN]: FieldAccessException: Field index 0 is out of bounds for length 0
[10:39:40 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49)
[10:39:40 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:218)
[10:39:40 WARN]:        at TabList-bukkit-5.6.6.jar//hu.montlikadani.tablist.ProtocolPackets.onPacketSending(ProtocolPackets.java:53)
[10:39:40 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[10:39:40 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[10:39:40 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547)
[10:39:40 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521)
[10:39:40 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99)
[10:39:40 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571)
[10:39:40 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472)
[10:39:40 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43)
[10:39:40 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252)
[10:39:40 WARN]:        at net.minecraft.network.NetworkManager.sendPacket(NetworkManager.java:432)
[10:39:40 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:379)
[10:39:40 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2157)
[10:39:40 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2143)
[10:39:40 WARN]:        at net.minecraft.server.players.PlayerList.d(PlayerList.java:967)
[10:39:40 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1569)
[10:39:40 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:440)
[10:39:40 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[10:39:40 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[10:39:40 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[10:39:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### TabList configuration files

hook:

  # Hook to PlaceholderAPI to use custom placeholders.
  placeholderapi: true

# Fake players that can be added to the player list.
fake-players:
  enabled: false

  # Do we count the added fake players to the %online-players% placeholder?
  count-fake-players-to-online-players: false

# If enabled, the gray color will not appear to other players when the player's game mode is spectator.
# The gray color will only show for the spectator player.
# Requires ProtocolLib!
remove-gray-color-from-tab-in-spectator: true

# true - does not count vanished players in %online-players% placeholder.
# Requires Essentials, SuperVanish, PremiumVanish or CMI plugin!
ignore-vanished-players-in-online-players: true

# true - count vanished staff in %staff-online% placeholder,
# but they need to have "tablist.onlinestaff" permission set.
# false - does not count vanished staff in the %staff-online% placeholder
# Requires Essentials, SuperVanish, PremiumVanish or CMI plugin!
count-vanished-staffs: false

# Hide player from player list when a player is AFK?
# Requires Essentials or CMI plugin!
hide-player-from-tab-when-afk: false

# Hide all players from the player list?
# This removes all players from the player list, but the player that has the
# group set is retained as it is not changed during removal, so your group
# will be restored if this option is disabled.
# Requires ProtocolLib to fix view distance issue! (https://github.com/montlikadani/TabList/issues/147)
hide-players-from-tablist: false

# Different player list in different world.
per-world-player-list:
  enabled: false

  # You can specify worlds, which will share the same list of players
  world-groups:

    # The key name, can be anything
    example1:
    - exampleWorld
    - exampleAnotherWorld
    exampleGroup2:
    - exampleWorld2
    - exampleAnotherWorld2

# Placeholders formatting
placeholder-format:

  # When the player changes the AFK status, change his tablist name format?
  afk-status:
    enable: true

    # Should the AFK format display in right or left side?
    # true - displays in right side
    # false - displays in left side
    show-in-right-or-left-side: true

    # Show player's group if the player is AFK?
    show-player-group: true

    # Format when the player is AFK.
    format-yes: '&7 [AFK]&r '

    # Format when the player is not AFK.
    format-no: ''

    # Sort AFK players to the bottom of the player list?
    sort-last: false
  time:

    # Time zones: https://www.mkyong.com/java/java-display-list-of-timezone-with-gmt/
    # Or google it: "what is my time zone"
    time-zone: GMT+1

    # Use system default time zone instead of searching for that?
    use-system-zone: false

    # Formats/examples: https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
    # Format of %server-time% placeholder.
    time-format: HH:mm

    # Format of %date% placeholder.
    date-format: dd/MM/yyyy

  # Ping color format for %ping% placeholder.
  ping:
    enable: true

    # https://github.com/montlikadani/TabList/wiki/Ping-or-tps-formatting
    formats:
    - '&a%ping% <= 200'
    - '&6%ping% >= 200'
    - '&c%ping% > 500'

  # TPS color format for %tps% placeholder.
  tps:
    enable: true

    # https://github.com/montlikadani/TabList/wiki/Ping-or-tps-formatting
    formats:
    - '&a%tps% > 18.0'
    - '&6%tps% == 16.0'
    - '&c%tps% < 16.0'

    # How many numbers do you want to display after "." in %tps% placeholder?
    # The number should be higher than 0.
    # Example: 3 = 19.14
    size: 2

  # Memory bar settings for %memory_bar% variable
  memory-bar:
    char: '|'
    size: 80
    colors:
      used: '&c'
      free: '&a'

      # When the server memory less than 80
      allocation: '&e'

      # When the server memory is on critical level (less than 40) and some resource need memory to run.
      released: '&6'

# Enable changing of prefix & suffix in player list?
change-prefix-suffix-in-tablist:
  enable: false

  # Refresh interval in server ticks.
  # Set to 0 if you don't want to refresh the groups.
  # If 0, then you will need to execute the /tl reload command to refresh the groups.
  refresh-interval: 4

  # Disable groups in these worlds.
  disabled-worlds:

    # Use the list as whitelist?
    use-as-whitelist: false
    list:
    - myWorldWithUpper

  # Automatically add groups from another plugins to the tablist groups.yml on every reload?
  # If a plugin does not support Vault, it will not be added.
  sync-plugins-groups-with-tablist: true

  # Hide player's group in player list when the player is vanished?
  # Requires Essentials, SuperVanish, PremiumVanish or CMI plugin!
  hide-group-when-player-vanished: false

  # Do you want to assign global group to normal groups?
  # true - "globalGroupPrefix + normalGroupPrefix"
  # false - "normalGroupPrefix"
  assign-global-group-to-normal: false

  # Prefer player's primary Vault group when assigning tablist group from groups.yml?
  # true - player will be assigned their primary vault group where possible
  # false - applies the group that has the higher priority in the permission plugin
  prefer-primary-vault-group: true

  # Follow the name tag visibility for players to show the name tag above player or not,
  # depending if a scoreboard team with visibility 'hidden' is exist.
  # true - Follows the name tag visibility and hides if there is a scoreboard team created with visibility 'hidden'
  # false - Always shows the name tag above player
  followNameTagVisibility: false

# Tablist objective types
# Shows your current health (with life indicator), your current ping or any NUMBER placeholder
# after the player's name (before the ping indicator).
tablist-object-type:

  # Types:
  # none - disables tablist objects
  # ping - player's ping
  # health - player's health
  # custom - custom placeholder
  type: none

  # How often should it refresh the values in seconds?
  refresh-interval: 3

  # In these worlds the objects will not be displayed
  disabled-worlds:
  - testingWorld
  object-settings:
    health:
      restricted-players:
      - exampleplayer
      - players

    # Custom placeholder - accepts only number-ending placeholders, like %level%
    custom:
      value: '%level%'

# Check for updates?
check-update: true

# Download new releases to "releases" folder?
# This only works if the "check-update" is true.
download-updates: true

# Log plugin messages to console?
logconsole: true

# This option monitors server performance. If the server's TPS is less than the set value,
# TabList will cancels all currently running schedulers to improve server performance.
# TabList will not restart these schedulers (ie animations, group updates, etc.),
# so you have to do it manually, by reconnecting to the server or by reloading the plugin.
# At values below 8-5, TabList is almost unable to stop its own running processes,
# as the server is already under a very heavy load.
# The values should be between 5-18
# If the value is below 5 or above 18, the default value will be 16.0
# To disable this feature set to -1
tps-performance-observation-value: -1.0

### Bug description

When a bedrock user enters the server i have errors in console, generating some lag

**Comment by montlikadani** [comment] 2023-01-01 10:13
Duplicate of https://github.com/montlikadani/TabList/issues/373

**Closed by montlikadani** 2023-01-01 10:13 UTC
Labels: Type: Unconfirmed
