### ISSUE TITLE
Prefixes disappear occasionally from the Tab List

### ISSUE THREAD

**Issue by Panczis** [montlikadani/TabList#387] opened 2023-02-20 08:42 UTC
### Type of bug

Other

### TabList version

[09:34:53 INFO]: TabList version 5.6.8 [09:34:53 INFO]: An ultimate animated tablist [09:34:53 INFO]: Author: montlikadani

### Software version

This server is running Paper version git-Paper-323 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: d2cb347) You are 83 version(s) behind

### Relevant plugins

**Plugins (25)**: _ajLeaderboards, AuthMe, AutoMessage, Citizens, ColoredBooked, DecentHolograms, Essentials, EssentialsSpawn, GrimAC, LogBlock, LPC, LuckPerms, NametagEdit, PlaceholderAPI, PrivateChest*, ServerListMotdSpigot, SimpleScore, SkinsRestorer, Statz, TabList, TreeAssist, UTitleAuth, Vault, WorldEdit, WorldGuard_

### TabList configuration files
```yml
hook:

  # Hook to PlaceholderAPI to use custom placeholders.
  placeholderapi: true

# This option monitors server performance. If the server's TPS is less than the set value,
# TabList will cancels all currently running schedulers to improve server performance.
# TabList will not restart these schedulers (ie animations, group updates, etc.),
# so you have to do it manually, by reconnecting to the server or by reloading the plugin.
# At values below 8-5, TabList is almost unable to stop its own running processes,
# as the server is already under a very heavy load.
# The values should be between 5-18
# If the value is below 5 or above 18, the default value will be 16.0
# To disable this feature set to -1
tps-performance-observation-value: -1.0

# Fake players that can be added to the player list.
fake-players:
  enabled: false

  # Do we count the added fake players to the %online-players% placeholder?
  count-fake-players-to-online-players: false

# If enabled, the gray color will not appear to other players when the player's game mode is spectator.
# The gray color will only show for the spectator player.
remove-gray-color-from-tab-in-spectator: false

# true - does not count vanished players in %online-players% placeholder.
# Requires Essentials, SuperVanish, PremiumVanish or CMI plugin!
ignore-vanished-players-in-online-players: false

# true - count vanished staff in %staff-online% placeholder,
# but they need to have "tablist.onlinestaff" permission set.
# false - does not count vanished staff in the %staff-online% placeholder
# Requires Essentials, SuperVanish, PremiumVanish or CMI plugin!
count-vanished-staffs: true

# Hide player from player list when a player is AFK?
# Requires Essentials or CMI plugin!
hide-player-from-tab-when-afk: false

# Hide all players from the player list?
# This removes all players from the player list, but the player that has the
# group set is retained as it is not changed during removal, so your group
# will be restored if this option is disabled.
hide-players-from-tablist: false

# Different player list in different world.
per-world-player-list:
  enabled: false

  # You can specify worlds, which will share the same list of players
  world-groups:

    # The key name, can be anything
    example1:
    - exampleWorld
    - exampleAnotherWorld
    exampleGroup2:
    - exampleWorld2
    - exampleAnotherWorld2

# Placeholders formatting
placeholder-format:

  # When the player changes the AFK status, change his tablist name format?
  afk-status:
    enable: true

    # Should the AFK format display in right or left side?
    # true - displays in right side
    # false - displays in left side
    show-in-right-or-left-side: false

    # Show player's group if the player is AFK?
    show-player-group: true

    # Format when the player is AFK.
    format-yes: '&#FF00F0 [AFK]&r '

    # Format when the player is not AFK.
    format-no: ''

    # Sort AFK players to the bottom of the player list?
    sort-last: false
  time:

    # Time zones: https://www.mkyong.com/java/java-display-list-of-timezone-with-gmt/
    # Or google it: "what is my time zone"
    time-zone: GMT0

    # Use system default time zone instead of searching for that?
    use-system-zone: false

    # Formats/examples: https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
    # Format of %server-time% placeholder.
    time-format: mm:HH

    # Format of %date% placeholder.
    date-format: dd/MM/yyyy

  # Ping color format for %ping% placeholder.
  ping:
    enable: true

    # https://github.com/montlikadani/TabList/wiki/Ping-or-tps-formatting
    formats:
    - '&a%ping% <= 200'
    - '&6%ping% >= 200'
    - '&c%ping% > 500'

  # TPS color format for %tps% placeholder.
  tps:
    enable: true

    # https://github.com/montlikadani/TabList/wiki/Ping-or-tps-formatting
    formats:
    - '&a%tps% > 18.0'
    - '&6%tps% == 16.0'
    - '&c%tps% < 16.0'

    # How many numbers do you want to display after "." in %tps% placeholder?
    # The number should be higher than 0.
    # Example: 3 = 19.14
    size: 2

# Enable changing of prefix & suffix in player list?
change-prefix-suffix-in-tablist:
  enable: true

  # Refresh interval in server ticks.
  # Set to 0 if you don't want to refresh the groups.
  # If 0, then you will need to execute the /tl reload command to refresh the groups.
  refresh-interval: 10

  # Disable groups in these worlds.
  disabled-worlds:

    # Use the list as whitelist?
    use-as-whitelist: false
    list:
    - myWorldWithUpper

  # Automatically add groups from another plugins to the tablist groups.yml on every reload?
  # If a plugin does not support Vault, it will not be added.
  sync-plugins-groups-with-tablist: false

  # Hide player's group in player list when the player is vanished?
  # Requires Essentials, SuperVanish, PremiumVanish or CMI plugin!
  hide-group-when-player-vanished: false

  # Do you want to assign global group to normal groups?
  # true - "globalGroupPrefix + normalGroupPrefix"
  # false - "normalGroupPrefix"
  assign-global-group-to-normal: false

  # Prefer player's primary Vault group when assigning tablist group from groups.yml?
  # true - player will be assigned their primary vault group where possible
  # false - applies the group that has the higher priority in the permission plugin
  prefer-primary-vault-group: false

  # Follow the name tag visibility for players to show the name tag above player or not,
  # depending if a scoreboard team with visibility 'hidden' is exist.
  # true - Follows the name tag visibility and hides if there is a scoreboard team created with visibility 'hidden'
  # false - Always shows the name tag above player
  followNameTagVisibility: false

# Tablist objective types
# Shows your current health (with life indicator), your current ping or any NUMBER placeholder
# after the player's name (before the ping indicator).
tablist-object-type:

  # How often should it refresh the values in seconds?
  refresh-interval: 3

  # The unique integer variable to be displayed.
  custom-value: '%level%'

  # In these worlds the objects will not be displayed
  disabled-worlds:
  - testingWorld

  # Types:
  # none - disables tablist objects
  # ping - player's ping
  # health - player's health
  # custom - custom placeholder
  type: ping

# Check for updates?
check-update: true

# Download new releases to "releases" folder?
# This only works if the "check-update" is true.
download-updates: false

# Log plugin messages to console?
logconsole: true
```

### Bug description

Hey! 
Im trying to work out some serious problem here :/
Maybe it's not that big of an issue, but that keeps me up all night and cant figure it out by myself so im trying to get some help here Boys and Girls!

So the problem is ... that sometimes, the prefixes just DISSAPPEAR (look at the screenshot) and now ... i can do /tl reload and everything is fine, but ... here comes the fun part ... when someone (No matter who) joins the server, BANG, it magically fixes for couple of minutes.
Setting reseting interval to some ticks is not working too :/ i can see that the tablist is "reloading" but the bugged nick without prefix and any formating is STILL THERE.

Btw, that bug can happens to anyone on my server.

![problem](https://user-images.githubusercontent.com/125865027/220055484-d93d2c6d-4610-4838-8a12-5892f3f82ba4.png)

**Comment by montlikadani** [comment] 2023-02-20 12:10
It will disappear because players probably having multiple groups set or the group changed at that time and needs a reload.

**Comment by Panczis** [comment] 2023-02-20 14:08
Ohhh. didnt think about that...


Now i realised that only players from groups : "Admin" "Prezes" "Moderator" "Helper" are missing prefix sometimes ... but not players from group "Gracz" that have only 1 group and it;s: "default" with prefix [GRACZ]

![admin](https://user-images.githubusercontent.com/125865027/220129208-94eefad9-3194-4878-88f1-eb94dd656fcf.jpg)
![prezes](https://user-images.githubusercontent.com/125865027/220129232-edc79fcc-49ad-430e-b76a-5f18137bbd7a.jpg)
![gracz](https://user-images.githubusercontent.com/125865027/220129242-18b96124-4455-47c0-91fd-5f0ad4fb65d5.jpg)

I will change groups to only 1 group ---- And I'll post latest information soon :)

**Comment by Panczis** [comment] 2023-02-20 15:45
Only my preffix just dissapeard from the tablist :/
But i've just removed "*" permission from group admin in lpeditor. maybe that'll do the work.

**Comment by montlikadani** [comment] 2023-02-20 19:12
Enable `prefer-primary-vault-group` in config

**Comment by Panczis** [comment] 2023-02-20 19:16
I'll try

**Comment by Panczis** [comment] 2023-02-20 20:23
Still ... 
![image](https://user-images.githubusercontent.com/125865027/220192326-999a1630-d39b-4020-85cd-e1c09e28e27b.png)

**Comment by Panczis** [comment] 2023-02-21 13:47
Any new Ideas my friend?

**Comment by montlikadani** [comment] 2023-02-21 15:41
Can you show your groups.yml file, send to **pastebin.com**

**Comment by montlikadani** [comment] 2023-02-21 16:22
I made some changes related to groups recognition, you can test the new build from [Actions](https://github.com/montlikadani/TabList/actions/workflows/gradle.yml) select the first one and find Artifacts.

**Comment by Panczis** [comment] 2023-02-22 00:43
Ohhh man :/ it's still glitching ... especially, when someone leaves the game, and repairs, when someone joins :/

![123](https://user-images.githubusercontent.com/125865027/220491451-4e5845d1-3e6b-4a41-ba80-bc4248d00a04.png)

**Comment by Panczis** [comment] 2023-02-22 13:38
Okay, my bad in last comment...
Now i've deleted ALL files of Tab-list from my server, closed it, opened it again, and config it ALL  the way up, to what im looking for AAAANDDD... still ... it's happening :/

![kerfsuss](https://user-images.githubusercontent.com/125865027/220635982-a677b7c0-06a6-40e2-96c3-ae9bd150f0d2.png)

**Comment by montlikadani** [comment] 2023-02-22 13:50
Removing plugins files makes no sense. The plugin won't fixes itself. Removing files means resets everything to the default.

**Comment by Panczis** [comment] 2023-02-22 13:55
No no no, i've removed my previous .jar too

**Comment by montlikadani** [comment] 2023-02-22 13:56
Which still makes no sense.

**Comment by Panczis** [comment] 2023-02-22 14:00
so what did you wanted me to do?
Yesterday, i've removed my previous .jar from plugin files and folder that .jar is creating.

Then, i've installed your new build (.jar) - started the server.
Then i saw, that everything from TAB, becomes default. so i've changed it.

I've changed it not by copy and paste from previous config, but writed it down in the new configs one by one

**Comment by montlikadani** [comment] 2023-02-22 14:11
Then I misunderstood, whatever. I am working on it to fix it.

**Comment by Panczis** [comment] 2023-02-22 14:11
Okay, im waiting my friend <3

**Comment by montlikadani** [comment] 2023-02-22 16:02
Can you send your groups.yml file

**Comment by montlikadani** [comment] 2023-02-22 16:32
Btw I can't reproduce this still after many attempts.

**Comment by Panczis** [comment] 2023-02-22 21:38
Ofcourse, i can send you my groups.yml





# This global group will be applied to all players
globalGroup:
  prefix: ''
  tabname: ''
  suffix: ''

groups:
  # Vault group name OR player name OR custom group name (custom is assigned via permission)
  exampleGroup:
    prefix: '&a[&cStaff&a]&6 '
    tabname: '%player-displayname%'
    suffix: '&7 <12>'
  
  Default:
    prefix: '&b&l<62>&r %luckperms_prefix%'
    tabname: '%player-displayname%'
    suffix: '&b&l <62>#'
  
  Admin:
    prefix: '#FF0000&l<62>&r %luckperms_prefix%'
    tabname: '%player-displayname%'
    suffix: '#FF0000&l <62>#'
  
  PlayerName:
    prefix: '&a[MyGroup]&7'
    tabname: '%player%'
    suffix: ''
  prezes:
    prefix: '#00FF00&l<62>&r %luckperms_prefix%'    
    tabname: '%player-displayname%'
    suffix: '#00FF00&l <62>#'
    
  streamer:
    prefix: '#B056FF&l<62>&r %luckperms_prefix%'    
    tabname: '%player-displayname%'
    suffix: '#B056FF&l <62>#'
    
  helper:
    prefix: '#D5FDFF&l<62>&r %luckperms_prefix%'
    tabname: '%player-displayname%'
    suffix: '#D5FDFF&l <62>#'    
  moderator:
    prefix: '#FFF000&l<62>&r %luckperms_prefix%'
    tabname: '%player-displayname%'
    suffix: '#FFF000&l <62>#'

**Comment by Panczis** [comment] 2023-02-22 21:42
Oh, and that's the TAB after not using /tl reload for 3 hours 
![3hours](https://user-images.githubusercontent.com/125865027/220765866-e9ab1351-d050-46f5-92e3-2754dd680e1f.png)

**Comment by Panczis** [comment] 2023-02-22 22:25
Ohhh. now they're all gone ;o

![lol](https://user-images.githubusercontent.com/125865027/220773808-28483642-72ec-4d17-80cb-3ac7a7edbc1c.png)

**Comment by Panczis** [comment] 2023-02-23 23:13
Hi, I was trying to make some changes in groups.yml like setting global group by just setting %luckyperms_prefix% etc. and still nothing :/ Even changed permissions from nte.admin (for example) to group.admin from vault... still nothing my friend :/

Any changes from you? <3

**Comment by montlikadani** [comment] 2023-02-24 05:09
Did you disabled the tablist option in nametagedit config?

**Comment by Panczis** [comment] 2023-02-24 15:06
Yes. 

I downloaded other plugin and everything works super fine 
![op](https://user-images.githubusercontent.com/125865027/221212605-cd604545-303c-4e06-a59c-e62c563cc114.png)

But thanks for you support anyways <3

**Closed** 2023-06-10 13:47 UTC
Labels: Type: Unconfirmed, Platform: Bukkit, Status: Can't reproduce
