### ISSUE TITLE
TabList not running opn minecraft 1.21.3

### ISSUE THREAD

**Issue by fp19641** [montlikadani/TabList#553] opened 2024-11-28 11:41 UTC
### Type of bug

Compatibility issue

### TabList version

5.7.7

### Software version

This server is running Paper version 1.21.3-67-master@d38624b (2024-11-27T20:28:58Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT) You are running the latest version Previous version: 1.21.3-65-7e789e8 (MC: 1.21.3)

### TabList configuration files

.

### Bug description

Tablist 5.7.7 not compatible with paper 1.21.3

**Comment by Jatc252** [comment] 2024-11-29 13:22
Duplicate of #546

**Closed as completed** 2024-11-30 18:03 UTC
Labels: Other: Duplicate, Platform: Bukkit
